Simulator api
git-gurus-itu-devops/itu-minitwit pull request #16
Opened 2024-02-16 12:27 UTC by silkeholmebonnen

2024-02-19 11:26 UTC, duckth requested changes

2024-02-19 11:26 UTC, duckth commented on simapi/sim_api.rb
> +  File.write('./latest_processed_sim_action_id.txt', parsed_command_id.to_i, mode: 'w') if parsed_command_id != -1
Probably a premature worry but we MIGHT run into concurrency-issues if we just use the regular File, not sure if it is thread-safe / atomic
But fine for now, just something to keep in mind

2024-02-19 11:26 UTC, duckth commented on simapi/sim_api.rb
> +  request_data = JSON.parse(request.body.read, symbolize_names: true)
What is the reasoning behind parsing request instead of using `params`?

2024-02-19 11:26 UTC, duckth commented on simapi/sim_api.rb
> +    return { 'status' => 400, 'error_msg' => error }.to_json
```suggestion
    return { status: 400, error_msg: error }.to_json
```

2024-02-19 11:26 UTC, duckth commented on simapi/sim_api.rb
> +    body ''
Is body needed here?

2024-02-20 16:03 UTC, duckth approved these changes

2024-02-22 08:54 UTC, fredpetersen reviewed
En enkelt kommentar. Ikke nødvendigvis afvist, men bare noget til eftertanke

2024-02-22 08:54 UTC, fredpetersen commented on simapi/sim_api.rb
> +  end
Tror det ville øge læsebarheden at hive `error` ud af den første if, også selvom vi "duplikerer" 2 linjers kode
et foreslag kunne være:
```suggestion
  if error 
    status 400
    body({ status: 400, error_msg: error }.to_json)
  elsif User.create(
    username: request_data[:username],
    email: request_data[:email],
    password: request_data[:pwd],
    password_confirmation: request_data[:pwd]
  )
      status 204
  else
    error = 'Something went wrong'
    status 400
    body({ status: 400, error_msg: error }.to_json)
  end
```

2024-02-22 09:45 UTC, fredpetersen approved these changes

2024-02-22 09:57 UTC, merged