Add Vagrantfile for VM Provisioning and update README
git-gurus-itu-devops/itu-minitwit pull request #17
Opened 2024-02-16 13:50 UTC by duckth

2024-02-20 09:19 UTC, fredpetersen commented on Vagrantfile
> +      provider.region = 'nyc1'
New york city er OK langt væk
```suggestion
      provider.region = 'fra1'
```

2024-02-20 10:03 UTC, duckth commented
Need to fix synced folder

2024-02-21 21:19 UTC, duckth commented
http://165.227.245.161:5001

2024-02-22 07:57 UTC, silkeholmebonnen commented
There are 3 different url mentioned in the PR; http://165.227.245.161:5001/ http://134.209.131.46:5000/ and http://67.205.156.216:5000/public but none of them works for me. On the first one I get an error message saying "You are not authorized to use this resource!" and the other ones just don't work. Which one do we use and is it supposed to work at the moment?

2024-02-22 09:36 UTC, duckth commented
> There are 3 different url mentioned in the PR; http://165.227.245.161:5001/ http://134.209.131.46:5000/ and http://67.205.156.216:5000/public but none of them works for me. On the first one I get an error message saying "You are not authorized to use this resource!" and the other ones just don't work. Which one do we use and is it supposed to work at the moment?

Apologies for the terrible communication about this:
http://165.227.245.161:5001/ (port 5001) is for the simulator API only. You need the credentails from the simulator to access it
http://165.227.245.161:5000/ (port 5000) is the web interface

The other URL's are outdated.

2024-02-22 09:38 UTC, duckth commented
I'll update the readme at some point

2024-02-22 09:40 UTC, fredpetersen approved these changes

2024-02-22 10:03 UTC, fredpetersen approved these changes

2024-02-22 10:10 UTC, A-Guldborg requested changes

2024-02-22 10:10 UTC, A-Guldborg commented on README.md
> +The Vagrantfile syncs the local repository to the VM so be sure to have a database in `db/minitwit.db`
```suggestion
The Vagrantfile syncs the local repository to the VM so be sure to have a database in `./db/minitwit.db`
```

2024-02-22 10:12 UTC, A-Guldborg approved these changes
LGTM

2024-02-22 10:13 UTC, merged