add sim api test to workflow
git-gurus-itu-devops/itu-minitwit pull request #40
Opened 2024-03-08 13:13 UTC by silkeholmebonnen

2024-03-10 22:42 UTC, A-Guldborg requested changes
In general looks very good :) 

I am thinking; Is it possible to move the simulator-related files into our `./simpapi/` folder?

It would also be very nice to verify, that a failing test will actually cause an error code that will reflect in our Github Actions workflow, so we know that we will see if any test fails in the future

2024-03-10 22:42 UTC, A-Guldborg commented on minitwit_simulator.py
Why is this file being source-controlled? I do not see any references of it anywhere in the workflow or the api test-code, but I might be wrong?

2024-03-12 15:09 UTC, silkeholmebonnen commented on minitwit_simulator.py
You're right it is not used. We just discussed using it later, so i just thought it would be nice to source control it. Same goes for `minitwit_scenerio.csv`

2024-03-12 15:41 UTC, silkeholmebonnen commented
> In general looks very good :)
> 
> I am thinking; Is it possible to move the simulator-related files into our `./simpapi/` folder?
> 
> It would also be very nice to verify, that a failing test will actually cause an error code that will reflect in our Github Actions workflow, so we know that we will see if any test fails in the future

I moved the test files into the `./simpapi/` folder.

In commit [verify test is failing in github actions](https://github.com/git-gurus-itu-devops/itu-minitwit/pull/40/commits/58ba3fe60c548d8ce499c827a81b9805110abca2) you can see that one test fails as expected.

2024-03-12 20:38 UTC, A-Guldborg commented
> > In general looks very good :)
> > I am thinking; Is it possible to move the simulator-related files into our `./simpapi/` folder?
> > It would also be very nice to verify, that a failing test will actually cause an error code that will reflect in our Github Actions workflow, so we know that we will see if any test fails in the future
> 
> I moved the test files into the `./simpapi/` folder.
> 
> In commit [verify test is failing in github actions](https://github.com/git-gurus-itu-devops/itu-minitwit/pull/40/commits/58ba3fe60c548d8ce499c827a81b9805110abca2) you can see that one test fails as expected @A-Guldborg

Looking at the GHA logs for the two failing commits in this repo I am one; a little worried about our pipeline not being consistent, and two; unsure that "forcing" the test to fail is actually what failed the workflow.

In the first failing commit, it seems to be the login step that somehow fails. Are we sure that it is not possible to move the Dockerfile to the same folder? 
![image](https://github.com/git-gurus-itu-devops/itu-minitwit/assets/95026056/989900fd-d6e4-4014-b6b4-8f65db360730)

For the second failing commit, which we expected to fail due to changing expected outcome, the error message is also talking about auth and dockerhub, and fails in the push to DockerHub step.
![image](https://github.com/git-gurus-itu-devops/itu-minitwit/assets/95026056/91a7d560-087e-4448-aeea-21afbedecfd5)

Might be that both issues are because of accessing the Dockerhub "too often" (If the two commits were added too soon after each other?). But it does indicate some issues with our pipeline and authentication with DockerHub.

I suggest we retry both moving the Dockerfile first, and after that attempting to make the step "Run minitwit api" fail with the same test-change as in the latter commit.

2024-03-15 10:46 UTC, silkeholmebonnen commented
@A-Guldborg in commit [4c78315](https://github.com/git-gurus-itu-devops/itu-minitwit/pull/40/commits/4c78315699b582f07cefbc7056139223423b20ab) 1 test failed as expected. I have moved all api related files into simapi except for `docker-compose-api-test.yaml` as I couldn't figure out how to make that work. You are welcome to try if you want to:)

2024-03-15 11:41 UTC, A-Guldborg approved these changes
> @A-Guldborg in commit [4c78315](https://github.com/git-gurus-itu-devops/itu-minitwit/pull/40/commits/4c78315699b582f07cefbc7056139223423b20ab) 1 test failed as expected. I have moved all api related files into simapi except for `docker-compose-api-test.yaml` as I couldn't figure out how to make that work. You are welcome to try if you want to:)

Might just be that it is simply not possible then. Thank you for the effort in trying! Otherwise LGTM and nice to see that the test fails and stops remaining steps as expected :)

2024-03-15 11:42 UTC, merged