add simulator test
git-gurus-itu-devops/itu-minitwit pull request #57
Opened 2024-03-31 13:35 UTC by silkeholmebonnen

This PR should close issue #38. It adds simulator test to workflow. 

The test makes sure that there are fewer than 10 errors in total, and checks that no errors of type `tweet`, `register`, `follow` or `unfollow`. This is to get around the fact that we usually get a few `ReadTimeout` and `ConnectionError`.  I also limited the simulator to only do a 1000 requests. I don't know if we want this or if we want to fire the 25000 requests of?

2024-04-01 19:04 UTC, A-Guldborg requested changes
I think we need to reduce the amount of docker images and try to use the main docker image we have which will mimick production more. Instead have steps in our workflow files that uses the main docker image and then pointing our tests towards that one / running our tests in that docker image.

Also, are we certain we cannot fix the errors (`ReadTimeout` and `ConnectionError`) that we get from the simulator? I mean, it seems we might handle many simultaneous requests badly so perhaps we should look into that? (In a separate PR possibly)

I don't know what you are thinking about these two points and if there could be any issues with that? Anyways, a couple things that I at least think we need to fix with this PR regardless of which way we decide to test and how we consider the two errors types :)

2024-04-02 16:36 UTC, silkeholmebonnen commented on simapi/minitwit_simulator_test.py
> +    # Check each line for the presence of "tweet"
I removed all comments. I don't think any comments are necessary. 

I guess we could do it the other way around as well, but this way makes more sense to me at least.

2024-04-02 16:47 UTC, silkeholmebonnen commented on simapi/Dockerfile-api-test
> +ENTRYPOINT pytest -s minitwit_sim_api_test.py && python ./minitwit_simulator.py "http://minitwit-api:5001" "./minitwit_scenario.csv" true > ./simulator_output.txt && pytest ./minitwit_simulator_test.
1. I think the other one is better practice but I didn't know how else to do it
2. First the API tests are run. Afterwards the simulator runs and the outcome of the simulator is tested. This is probably not the best way to do it, but it works. But any other ways of doing it are very welcome:)
3. As far as I understand we did not need to expose 5001. This is just the test image so why would we expose it?

2024-04-02 19:19 UTC, A-Guldborg commented on simapi/Dockerfile-api-test
> +ENTRYPOINT pytest -s minitwit_sim_api_test.py && python ./minitwit_simulator.py "http://minitwit-api:5001" "./minitwit_scenario.csv" true > ./simulator_output.txt && pytest ./minitwit_simulator_test.
For 1. and 2.: If it works I agree lets use it :)
For 3.: Sure, I don't know why we exposed it in the first place but you are probably right! :)

2024-04-03 20:14 UTC, merged